-- Run this in Supabase SQL Editor.
create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null,
  mode text not null,
  tier text not null,
  points integer not null default 0,
  tests integer not null default 1,
  icon text default '👤',
  created_at timestamptz not null default now(),
  unique(name, mode)
);

alter table public.players enable row level security;

drop policy if exists "Public can read players" on public.players;
create policy "Public can read players"
on public.players for select
to anon, authenticated
using (true);

drop policy if exists "Signed in admins can insert players" on public.players;
create policy "Signed in admins can insert players"
on public.players for insert
to authenticated
with check (true);

drop policy if exists "Signed in admins can update players" on public.players;
create policy "Signed in admins can update players"
on public.players for update
to authenticated
using (true)
with check (true);

drop policy if exists "Signed in admins can delete players" on public.players;
create policy "Signed in admins can delete players"
on public.players for delete
to authenticated
using (true);

-- Optional demo data:
insert into public.players (name,mode,tier,points,tests,icon) values
('ClutchKing','AXE PVP','HT1',982,14,'⚔️'),
('VoidX','NETPOT','MT1',955,11,'🌑'),
('Deet','DIA KIT','HT2',918,9,'🔥'),
('PixelRush','SMP KIT','LT2',876,12,'⚡'),
('Bedrocker','UHC','HT3',820,8,'⛏️'),
('ComboGod','E-MACE','MT3',794,10,'🎯'),
('SkyPvper','CART PVP','HT4',730,7,'☁️'),
('NetherAce','VANILLA CRYSTAL','LT4',698,9,'🌋'),
('IronFang','TANK','HT5',620,6,'🛡️'),
('BlockStorm','SPEAR MACE','LT5',584,8,'🧱')
on conflict (name,mode) do nothing;